application: save-tasks
runtime: python
version: 1
api_version: 1
#threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: main.py
